# Generated by Django 5.0.3 on 2024-04-02 00:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("football_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="playerbio",
            table="player",
        )
    ]
